import { useState, useCallback, useRef } from "react";

// ── Types ──────────────────────────────────────────────────────────────────────

interface Question {
  id: number;
  type: "mcq" | "sata" | "ordered" | "calculation" | "exhibit";
  stem: string;
  options: Record<string, string>;
  answer: string[];
}

interface TestData {
  title: string;
  generated_at: string;
  question_count: number;
  sources: string[];
  questions: Question[];
}

type AnswerState = Record<number, string[]>;
type RevealState = Record<number, boolean>;

// ── Helpers ────────────────────────────────────────────────────────────────────

function isCorrect(question: Question, selected: string[]): boolean {
  if (!selected.length) return false;
  const a = [...question.answer].sort();
  const b = [...selected].sort();
  return a.length === b.length && a.every((v, i) => v === b[i]);
}

function getTypeLabel(type: Question["type"]): string {
  const map: Record<Question["type"], string> = {
    mcq: "MCQ",
    sata: "SATA",
    ordered: "ORDER",
    calculation: "CALC",
    exhibit: "EXHIBIT",
  };
  return map[type] ?? type.toUpperCase();
}

function getTypeColor(type: Question["type"]): string {
  const map: Record<Question["type"], string> = {
    mcq: "#4f8ef7",
    sata: "#e07b3f",
    ordered: "#8b5cf6",
    calculation: "#10b981",
    exhibit: "#ec4899",
  };
  return map[type] ?? "#888";
}

// ── Upload Screen ──────────────────────────────────────────────────────────────

function UploadScreen({ onLoad }: { onLoad: (data: TestData) => void }) {
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const processFile = useCallback(
    (file: File) => {
      if (!file.name.endsWith(".json")) {
        setError("Please upload a .json file generated by nclex_test_generator.py");
        return;
      }
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = JSON.parse(e.target?.result as string) as TestData;
          if (!data.questions || !Array.isArray(data.questions)) {
            throw new Error("Invalid format: missing questions array");
          }
          onLoad(data);
        } catch (err) {
          setError(`Could not parse file: ${(err as Error).message}`);
        }
      };
      reader.readAsText(file);
    },
    [onLoad]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) processFile(file);
    },
    [processFile]
  );

  return (
    <div style={styles.uploadPage}>
      <div style={styles.uploadCard}>
        <div style={styles.logoMark}>Rx</div>
        <h1 style={styles.uploadTitle}>NCLEX Practice</h1>
        <p style={styles.uploadSub}>Load a generated test to begin</p>

        <div
          style={{
            ...styles.dropZone,
            ...(dragging ? styles.dropZoneActive : {}),
          }}
          onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={handleDrop}
          onClick={() => inputRef.current?.click()}
        >
          <input
            ref={inputRef}
            type="file"
            accept=".json"
            style={{ display: "none" }}
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) processFile(file);
            }}
          />
          <div style={styles.dropIcon}>⬆</div>
          <p style={styles.dropLabel}>Drop your <code style={styles.code}>_nclex_test.json</code> here</p>
          <p style={styles.dropSub}>or click to browse</p>
        </div>

        {error && <p style={styles.errorMsg}>{error}</p>}

        <p style={styles.hint}>
          Generate a test first with <code style={styles.code}>nclex_test_generator.py</code>
        </p>
      </div>
    </div>
  );
}

// ── Question Card ──────────────────────────────────────────────────────────────

function QuestionCard({
  question,
  index,
  selected,
  revealed,
  onSelect,
  onReveal,
}: {
  question: Question;
  index: number;
  selected: string[];
  revealed: boolean;
  onSelect: (id: number, option: string) => void;
  onReveal: (id: number) => void;
}) {
  const isSata = question.type === "sata";
  const answered = selected.length > 0;
  const correct = isCorrect(question, selected);

  return (
    <div style={styles.card}>
      {/* Header row */}
      <div style={styles.cardHeader}>
        <span style={styles.qNumber}>Q{question.id}</span>
        <span
          style={{
            ...styles.typeBadge,
            backgroundColor: getTypeColor(question.type) + "22",
            color: getTypeColor(question.type),
            borderColor: getTypeColor(question.type) + "55",
          }}
        >
          {getTypeLabel(question.type)}
          {isSata && " — Select all that apply"}
        </span>
      </div>

      {/* Stem */}
      <p style={styles.stem}>{question.stem}</p>

      {/* Options */}
      <div style={styles.options}>
        {Object.entries(question.options).map(([key, text]) => {
          const isSelected = selected.includes(key);
          const isAnswer = question.answer.includes(key);

          let optionStyle = styles.option;
          if (revealed) {
            if (isAnswer) optionStyle = { ...styles.option, ...styles.optionCorrect };
            else if (isSelected && !isAnswer) optionStyle = { ...styles.option, ...styles.optionWrong };
          } else if (isSelected) {
            optionStyle = { ...styles.option, ...styles.optionSelected };
          }

          return (
            <button
              key={key}
              style={optionStyle}
              onClick={() => !revealed && onSelect(question.id, key)}
              disabled={revealed}
            >
              <span style={styles.optionKey}>{key}</span>
              <span style={styles.optionText}>{text}</span>
              {revealed && isAnswer && <span style={styles.checkmark}>✓</span>}
              {revealed && isSelected && !isAnswer && <span style={styles.xmark}>✗</span>}
            </button>
          );
        })}
      </div>

      {/* Action row */}
      <div style={styles.cardFooter}>
        {!revealed ? (
          <button
            style={{
              ...styles.revealBtn,
              opacity: answered ? 1 : 0.4,
              cursor: answered ? "pointer" : "default",
            }}
            onClick={() => answered && onReveal(question.id)}
            disabled={!answered}
          >
            Check Answer
          </button>
        ) : (
          <div
            style={{
              ...styles.resultBadge,
              backgroundColor: correct ? "#10b98122" : "#ef444422",
              color: correct ? "#10b981" : "#ef4444",
              borderColor: correct ? "#10b98155" : "#ef444455",
            }}
          >
            {correct ? "✓ Correct" : "✗ Incorrect"}
          </div>
        )}
      </div>

    </div>
  );
}

// ── Score Summary ──────────────────────────────────────────────────────────────

function ScoreSummary({
  data,
  answers,
  revealed,
  onReset,
}: {
  data: TestData;
  answers: AnswerState;
  revealed: RevealState;
  onReset: () => void;
}) {
  const revealedIds = Object.keys(revealed).map(Number);
  const totalRevealed = revealedIds.length;
  const totalCorrect = revealedIds.filter((id) => {
    const q = data.questions.find((q) => q.id === id);
    return q && isCorrect(q, answers[id] ?? []);
  }).length;

  const pct = totalRevealed > 0 ? Math.round((totalCorrect / totalRevealed) * 100) : 0;

  return (
    <div style={styles.scoreSummary}>
      <div style={styles.scoreRow}>
        <div style={styles.scoreStat}>
          <span style={styles.scoreNum}>{totalCorrect}/{totalRevealed}</span>
          <span style={styles.scoreLabel}>Answered</span>
        </div>
        <div style={{ ...styles.scoreStat, borderLeft: "1px solid #2a2a3a" }}>
          <span
            style={{
              ...styles.scoreNum,
              color: pct >= 70 ? "#10b981" : pct >= 50 ? "#f59e0b" : "#ef4444",
            }}
          >
            {pct}%
          </span>
          <span style={styles.scoreLabel}>Score</span>
        </div>
        <div style={{ ...styles.scoreStat, borderLeft: "1px solid #2a2a3a" }}>
          <span style={styles.scoreNum}>{data.question_count - totalRevealed}</span>
          <span style={styles.scoreLabel}>Remaining</span>
        </div>
      </div>
      <button style={styles.resetBtn} onClick={onReset}>
        Load New Test
      </button>
    </div>
  );
}

// ── Main App ───────────────────────────────────────────────────────────────────

export default function Tester() {
  const [testData, setTestData] = useState<TestData | null>(null);
  const [answers, setAnswers] = useState<AnswerState>({});
  const [revealed, setRevealed] = useState<RevealState>({});
  const [filter, setFilter] = useState<"all" | Question["type"]>("all");

  const handleLoad = useCallback((data: TestData) => {
    setTestData(data);
    setAnswers({});
    setRevealed({});
    setFilter("all");
  }, []);

  const handleSelect = useCallback((id: number, option: string) => {
    setAnswers((prev) => {
      const q = testData?.questions.find((q) => q.id === id);
      if (!q) return prev;
      const isSata = q.type === "sata";
      const current = prev[id] ?? [];
      if (isSata) {
        return {
          ...prev,
          [id]: current.includes(option)
            ? current.filter((o) => o !== option)
            : [...current, option],
        };
      }
      return { ...prev, [id]: [option] };
    });
  }, [testData]);

  const handleReveal = useCallback((id: number) => {
    setRevealed((prev) => ({ ...prev, [id]: true }));
  }, []);

  const handleReset = useCallback(() => {
    setTestData(null);
    setAnswers({});
    setRevealed({});
  }, []);

  if (!testData) return <UploadScreen onLoad={handleLoad} />;

  const types = Array.from(new Set(testData.questions.map((q) => q.type)));
  const filtered =
    filter === "all"
      ? testData.questions
      : testData.questions.filter((q) => q.type === filter);

  return (
    <div style={styles.app}>
      {/* Sidebar */}
      <aside style={styles.sidebar}>
        <div style={styles.sidebarLogo}>Rx</div>
        <div style={styles.sidebarTitle}>{testData.title}</div>
        <div style={styles.sidebarMeta}>
          {testData.question_count} questions
        </div>
        <div style={styles.sidebarMeta} title={testData.sources.join(", ")}>
          {testData.sources.slice(0, 2).join(", ")}
          {testData.sources.length > 2 && ` +${testData.sources.length - 2}`}
        </div>

        <div style={styles.filterSection}>
          <div style={styles.filterLabel}>Filter by type</div>
          {(["all", ...types] as Array<"all" | Question["type"]>).map((t) => (
            <button
              key={t}
              style={{
                ...styles.filterBtn,
                ...(filter === t ? styles.filterBtnActive : {}),
              }}
              onClick={() => setFilter(t)}
            >
              {t === "all" ? "All types" : getTypeLabel(t as Question["type"])}
              {t !== "all" && (
                <span
                  style={{
                    ...styles.filterDot,
                    backgroundColor: getTypeColor(t as Question["type"]),
                  }}
                />
              )}
            </button>
          ))}
        </div>

        <ScoreSummary
          data={testData}
          answers={answers}
          revealed={revealed}
          onReset={handleReset}
        />
      </aside>

      {/* Main content */}
      <main style={styles.main}>
        <div style={styles.questionList}>
          {filtered.map((q, i) => (
            <QuestionCard
              key={q.id}
              question={q}
              index={i}
              selected={answers[q.id] ?? []}
              revealed={!!revealed[q.id]}
              onSelect={handleSelect}
              onReveal={handleReveal}
            />
          ))}
        </div>
      </main>
    </div>
  );
}

// ── Styles ─────────────────────────────────────────────────────────────────────

const styles: Record<string, React.CSSProperties> = {
  // Upload
  uploadPage: {
    minHeight: "100vh",
    backgroundColor: "#0d0d14",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadCard: {
    background: "#13131f",
    border: "1px solid #2a2a3a",
    borderRadius: 16,
    padding: "48px 56px",
    maxWidth: 480,
    width: "90%",
    textAlign: "center",
  },
  logoMark: {
    fontSize: 40,
    fontWeight: 700,
    color: "#4f8ef7",
    marginBottom: 8,
    letterSpacing: "-1px",
  },
  uploadTitle: {
    color: "#e8e6f0",
    fontSize: 28,
    fontWeight: 700,
    margin: "0 0 6px",
    letterSpacing: "-0.5px",
  },
  uploadSub: {
    color: "#666",
    fontSize: 14,
    margin: "0 0 32px",
    fontFamily: "'Courier New', monospace",
  },
  dropZone: {
    border: "2px dashed #2a2a3a",
    borderRadius: 12,
    padding: "36px 24px",
    cursor: "pointer",
    transition: "border-color 0.2s, background 0.2s",
    marginBottom: 16,
  },
  dropZoneActive: {
    borderColor: "#4f8ef7",
    background: "#4f8ef708",
  },
  dropIcon: {
    fontSize: 28,
    marginBottom: 10,
    color: "#4f8ef7",
  },
  dropLabel: {
    color: "#ccc",
    fontSize: 15,
    margin: "0 0 4px",
  },
  dropSub: {
    color: "#555",
    fontSize: 13,
    margin: 0,
  },
  code: {
    fontFamily: "'Courier New', monospace",
    background: "#1e1e2e",
    padding: "1px 5px",
    borderRadius: 4,
    fontSize: "0.9em",
    color: "#a78bfa",
  },
  errorMsg: {
    color: "#ef4444",
    fontSize: 13,
    margin: "12px 0 0",
  },
  hint: {
    color: "#444",
    fontSize: 12,
    marginTop: 24,
    fontFamily: "'Courier New', monospace",
  },

  // App layout
  app: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0d0d14",
    color: "#e8e6f0",
  },
  sidebar: {
    width: 240,
    minWidth: 240,
    background: "#0f0f1a",
    borderRight: "1px solid #1e1e2e",
    padding: "28px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    position: "sticky",
    top: 0,
    height: "100vh",
    overflowY: "auto",
  },
  sidebarLogo: {
    fontSize: 30,
    fontWeight: 700,
    color: "#4f8ef7",
    marginBottom: 8,
    letterSpacing: "-1px",
  },
  sidebarTitle: {
    fontSize: 13,
    color: "#bbb",
    fontWeight: 600,
    lineHeight: 1.4,
    marginBottom: 4,
  },
  sidebarMeta: {
    fontSize: 11,
    color: "#555",
    fontFamily: "'Courier New', monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  filterSection: {
    marginTop: 24,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  filterLabel: {
    fontSize: 10,
    color: "#444",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    marginBottom: 6,
    fontFamily: "'Courier New', monospace",
  },
  filterBtn: {
    background: "transparent",
    border: "none",
    color: "#666",
    fontSize: 13,
    padding: "6px 10px",
    borderRadius: 6,
    cursor: "pointer",
    textAlign: "left",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transition: "background 0.15s, color 0.15s",
  },
  filterBtnActive: {
    background: "#1e1e2e",
    color: "#e8e6f0",
  },
  filterDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
  },

  // Score
  scoreSummary: {
    marginTop: "auto",
    paddingTop: 24,
    borderTop: "1px solid #1e1e2e",
  },
  scoreRow: {
    display: "flex",
    marginBottom: 14,
  },
  scoreStat: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "8px 0",
  },
  scoreNum: {
    fontSize: 20,
    fontWeight: 700,
    color: "#e8e6f0",
    lineHeight: 1,
  },
  scoreLabel: {
    fontSize: 10,
    color: "#555",
    marginTop: 3,
    fontFamily: "'Courier New', monospace",
  },
  resetBtn: {
    width: "100%",
    background: "transparent",
    border: "1px solid #2a2a3a",
    color: "#888",
    borderRadius: 8,
    padding: "8px 0",
    fontSize: 12,
    cursor: "pointer",
    transition: "border-color 0.15s, color 0.15s",
  },

  // Main
  main: {
    flex: 1,
    padding: "32px 40px",
    overflowY: "auto",
  },
  questionList: {
    maxWidth: 760,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },

  // Card
  card: {
    background: "#13131f",
    border: "1px solid #1e1e2e",
    borderRadius: 12,
    padding: "24px 28px",
    transition: "border-color 0.2s",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  qNumber: {
    fontSize: 11,
    fontWeight: 700,
    color: "#555",
    fontFamily: "'Courier New', monospace",
    letterSpacing: "0.05em",
  },
  typeBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: 4,
    border: "1px solid",
    fontFamily: "'Courier New', monospace",
    letterSpacing: "0.05em",
  },
  stem: {
    fontSize: 15,
    lineHeight: 1.65,
    color: "#ddd",
    margin: "0 0 18px",
  },
  options: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 16,
  },
  option: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    background: "#0d0d14",
    border: "1px solid #1e1e2e",
    borderRadius: 8,
    padding: "11px 14px",
    cursor: "pointer",
    textAlign: "left",
    color: "#bbb",
    fontSize: 14,
    lineHeight: 1.5,
    transition: "border-color 0.15s, background 0.15s",
  },
  optionSelected: {
    borderColor: "#4f8ef7",
    background: "#4f8ef710",
    color: "#e8e6f0",
  },
  optionCorrect: {
    borderColor: "#10b981",
    background: "#10b98110",
    color: "#10b981",
    cursor: "default",
  },
  optionWrong: {
    borderColor: "#ef4444",
    background: "#ef444410",
    color: "#ef4444",
    cursor: "default",
  },
  optionKey: {
    fontFamily: "'Courier New', monospace",
    fontWeight: 700,
    fontSize: 13,
    minWidth: 18,
    color: "inherit",
    opacity: 0.7,
  },
  optionText: {
    flex: 1,
  },
  checkmark: {
    color: "#10b981",
    fontWeight: 700,
    marginLeft: "auto",
    paddingLeft: 8,
  },
  xmark: {
    color: "#ef4444",
    fontWeight: 700,
    marginLeft: "auto",
    paddingLeft: 8,
  },

  // Footer
  cardFooter: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  revealBtn: {
    background: "#4f8ef7",
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    padding: "8px 20px",
    borderRadius: 8,
    transition: "opacity 0.15s",
  },
  resultBadge: {
    fontSize: 13,
    fontWeight: 600,
    padding: "6px 14px",
    borderRadius: 8,
    border: "1px solid",
    fontFamily: "'Courier New', monospace",
  },

  // Rationale
};