import React, { useState, useRef, useCallback } from "react";
import { DropZone } from "./DropZone";
import { TestData } from "@/types";

export const UploadScreen = ({ onLoad }: { onLoad: (data: TestData) => void }) => {
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const processFile = useCallback(
    (file: File) => {
      if (!file.name.endsWith(".json")) {
        setError("Please upload a .json file generated by nclex_test_generator.py");
        return;
      }
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = JSON.parse(e.target?.result as string) as TestData;
          if (!data.questions || !Array.isArray(data.questions)) {
            throw new Error("Invalid format: missing questions array");
          }
          onLoad(data);
        } catch (err) {
          setError(`Could not parse file: ${(err as Error).message}`);
        }
      };
      reader.readAsText(file);
    },
    [onLoad]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) processFile(file);
    },
    [processFile]
  );

  return (
    <div className="min-h-screen bg-[#0d0d14] flex items-center justify-center">
      <div className="bg-[#13131f] border border-[#2a2a3a] rounded-2xl px-14 py-12 max-w-[480px] w-[90%] text-center">
        <div className="text-[40px] font-bold text-[#4f8ef7] mb-2 tracking-tight">Glo Rx</div>
        <h1 className="text-[#e8e6f0] text-[28px] font-bold mb-1.5 tracking-tight">NCLEX Practice</h1>
        <p className="text-[#666] text-sm font-mono mb-8">Load a generated test to begin</p>

        <DropZone dragging={dragging} setDragging={setDragging} handleDrop={handleDrop} inputRef={inputRef} processFile={processFile} />

        {error && <p className="text-[#ef4444] text-[13px] mt-3">{error}</p>}

        <p className="text-[#444] text-xs mt-6 font-mono">
          Generate a test first with <code className="font-mono bg-[#1e1e2e] px-1.5 py-px rounded text-[0.9em] text-[#a78bfa]">nclex_test_generator.py</code>
        </p>
      </div>
    </div>
  );
}